version: '3'

services:
  db:
    build: ./db/Dockerfile
    image: postgres
    port: "3306:3306"
    environment: POSTGRES_DB=postgres POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

    depends_on: db

  frontend:
    build: ./frontend/Dockerfile

    depends_on: backend
